TheCluelessCook/Controllers/MealPlannerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TheCluelessCook.Data;
using TheCluelessCook.Data.Models;
using TheCluelessCook.Models.Planner;

namespace TheCluelessCook.Controllers
{
    public class MealPlannerController : Controller
    {
        private readonly IRecipe _recipeService;
        private readonly IPlanner _plannerService;
        private readonly UserManager<ApplicationUser> _userManager;

        public MealPlannerController(IRecipe recipeService, IPlanner plannerService, UserManager<ApplicationUser> userManager)
        {
            _recipeService = recipeService;
            _plannerService = plannerService;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            // Load in the recipe details for each day of the week
            // Get the user id
            var _curUser = _userManager.GetUserId(User);
            // Pass User Id in order to get list of week details
            var _weekDetails = _plannerService.GetByUser(_curUser)
                .Select(detail => new DayDetailModel
                {
                    Id = detail.Id,
                    Date = detail.Date,
                    Day = detail.Day,
                    recipe = detail.Recipe,
                    UserBestTime = detail.UserBestEatenAt
                });

            var model = new MealPlannerIndexModel
            {
                days = GetCurrentWeek(),
                details = _weekDetails
            };

            return View(model);
        }

        public IActionResult Plan()
        {
            return View();
        }

        private IEnumerable<WeeklyPlanAccordianModel> GetCurrentWeek()
        {
            // Build out the week section section
            DateTime _today = DateTime.Now;
            int _currentDay = (int)_today.DayOfWeek;

            // Get the list of days
            var _WeekDetails = Enumerable.Range(0, 7)
                .Select(Days => new WeeklyPlanAccordianModel
                {
                    Id = _today.AddDays(Days).ToString(),
                    Date = _today.AddDays(Days).Day.ToString(),
                    Day = _today.AddDays(Days).DayOfWeek.ToString()
                }).ToList();

            return _WeekDetails;
        }
    }
}

TheCluelessCook/Controllers/ShoppingListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace TheCluelessCook.Controllers
{
    public class ShoppingListController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

TheCluelessCook/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using TheCluelessCook.Data.Models
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>The Clueless Cook</title>
    <!--CSS SECTION-->
    <environment include="Development">
        <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
        <script src="https://kit.fontawesome.com/c7ce2f3b80.js"></script>
    </environment>
    <environment exclude="Development">
        <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
        <script src="https://kit.fontawesome.com/c7ce2f3b80.js"></script>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <!--SCRIPT SECTION-->
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    @RenderSection("Scripts", required: false)
</head>
<body>
    <header>
        <div class="container">
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">The Clueless Cook</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @if (SignInManager.IsSignedIn(User))
                {
                    <div class="navbar-collapse collapse d-sm-inline-flex">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item">
                                <a class="nav-link text-success" asp-controller="MealPlanner" asp-action="Index">Prepare</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-success" asp-controller="MealPlanner" asp-action="Plan">Plan</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-success" asp-controller="ShoppingList" asp-action="Index">Shop</a>
                            </li>
                        </ul>
                    </div>
                }
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                </div>
            </nav>
        </div>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            <div class="pb-2"></div>
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - The Clueless Cook - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
</body>
</html>